- name: Check if the directory exists
  ansible.builtin.stat:
    path: "{{ item }}"
  register: dir_to_check
  with_items: "{{ addons_directory }}"

- name: Set Addons Dir
  set_fact:
    addon_dir: "{{ item.stat.path }}"
  when: item.stat.isdir is defined and item.stat.isdir
  with_items: "{{ dir_to_check.results }}"

- name: Create pool folder
  shell: mkdir -p "{{ addon_dir }}{{ item.pool }}"
  with_items: "{{ git_repos }}"

- name: Performance a git Clone
  shell: git clone -b {{ odoov }} {{ item.1.url }}
  args:
    chdir: "{{ addon_dir }}{{ item.0.pool }}"
  with_subelements: 
    - "{{ git_repos }}"
    - origin