---
- name: ADDING CNAME RECORD ON CLOUDFLARE
  community.general.cloudflare_dns:
    zone: "{{ item.domain }}"
    record: "{{ item.host }}"
    type: "{{ item.type }}"
    value: "{{ item.ip }}"
    api_token: "{{apitoken}}"
    state: present
  with_items: "{{ dnsrecords.dns }}"