---
- name: creat user
  user:
    name: "{{ username }}"
    shell: /sbin/nologin
    append: yes
    state: present
  become: true

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '{{ username }}.pub') }}"