---
- name: creat user
  user:
    name: "{{ item.username }}"
    shell: /sbin/nologin
    append: yes
    state: present
  become: true
  with_items: "{{ data.users }}"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', '{{ item.key }}.pub') }}"
  when: item.key is defined
  with_items: "{{ data.users }}"