---
- name: Create NGINX VirtualHost
  template:
    src: "{{ item.odoov }}.conf.j2"
    dest: /etc/nginx/sites-available/{{ item.odoov }}.{{ item.company }}.{{ item.domain }}
  with_items: "{{ data.vhost }}"

- name: Create NGINX VirtualHost_symbLink
  file:
    src: /etc/nginx/sites-available/{{ item.odoov }}.{{ item.company }}.{{ item.domain }}
    dest: /etc/nginx/sites-enabled/{{ item.odoov }}.{{ item.company }}.{{ item.domain }}
    state: link
  with_items: "{{ data.vhost }}"
   
- name: restart_nginx
  service: name=nginx state=reloaded