- name: Coment default repo
  ansible.builtin.lineinfile:
    path: 
      - /etc/apt/sources.list.d/ceph.list
      - /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb'
    line: '#deb'

- name: Add Proxmox 8 Repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
  when: ansible_distribution_major_version == "12"

- name: Add Proxmox 7 Repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
  when: ansible_distribution_major_version == "11"

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400