- name: Get disk size
  shell: df  / --output\=avail | tail -1 |  awk '{gsub(/^[ \t]+/,""); print (($0/1024)/1024) }' 
  register: disk_size

- block:
  - name: Backup ADDONS
    shell: tar -cvf /root/addons.tar.gz "{{ home_directory }}"

  - name: Get Directory list
    shell:
      chdir: "{{ home_directory }}"
      cmd: ls -d */ 
    register: directories

  - name: Performance a git pull
    shell: git pull origin {{ odoov }} | tee /root/{{ item [:-1] }}.log
    args:
      chdir: "{{ home_directory }}{{ item }}"
    with_items: "{{ directories.stdout_lines}}"

  when: disk_size.stdout | int >= 3