- name: Get Node Identity
  set_fact:
    node_identity: "{{ ansible_default_ipv4.address [3:7] }}"

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: "true"
    cache_valid_time: 86400

- name: Install Nginx
  ansible.builtin.apt:
    name: 
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Add Cront to renew CertBot Certificates
  ansible.builtin.cron:
    name: ReNew CertBot Certificates
    day: "1"
    hour: "23"
    minute: "50"
    user: root
    job: "certbot renew"

- name: Create nginx ssl folder
  file:
    path: "/etc/nginx/ssl"
    state: directory

- name: Copy Certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
  with_items: 
    - binhex.cloud.full.crt
    - binhex.cloud.private.crt

- name: Delete Old default symbLink && index.html
  file:
    path: "{{ item }}"
    state: absent
  with_items: 
    - /etc/nginx/sites-enabled/default
    - /usr/share/nginx/html/index.html

- name: Copy Defaults virtual hosts
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
  with_items:
    - default
    - mantenimiento.conf

- name: Create default VirtualHost_symbLink
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/00-default
    state: link

- name: Set custom  
  template:
    src: "files/{{ item }}"
    dest: /usr/share/nginx/html/{{ item [:-3] }}
  with_items:
    - custom_50x.html.j2
    - custom_403.html.j2
    - custom_404.html.j2
    - maintenance.html.j2

- name: restart_nginx
  service: name=nginx state=reloaded
