---
- name: creat user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: present
  
- name: creat ssh directory
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '{{ username }}.pub') }}"
  