---
- name: creat user
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    state: present
  with_items: "{{ usersdata.users }}"
  
- name: creat ssh directory
  file:
    path: "/home/{{ usersdata.users }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
  with_items: "{{ usersdata.users }}"
  
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', '{{ item.key }}.pub') }}"
  when: item.key is defined
  with_items: "{{ usersdata.users }}"
  