---
- name: Install Sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Config sudo
  copy:
    content: "{{ item.username }} ALL=(ALL:ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/{{ item.username }}
    mode: 0440
  with_items: "{{ data.users }}"

- name: Add user to Sudo group
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: sudo
  with_items: "{{ data.users }}"