---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Config sudo
  copy:
    content: "{{ item.username }} ALL=(ALL:ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/{{ item.username }}
    mode: 0440
  with_items: "{{ data.users }}"

- name: Add user to Sudo group
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: sudo
  when: item.sudo is defined
  with_items: "{{ data.users }}"