- name: ADD NGINX VIRTUAL HOST CERTBOT
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  vars:
    data: "{{ lookup('file', 'json-files/dns.json') | from_json }}"
  roles:
    - add-nginx-host-cerbot