- name: ADD DNS RECORD
  hosts: localhost
  gather_facts: false
  vars:
    dnsrecords: "{{ lookup('file', 'json-files/dns.json') | from_json }}"
    apitoken: "ZIcdybXr42m8meUstgFHK-gzhgVa9HVhkvS0A5dT"
  roles:
    - add-dns-a-record

- name: ADD NGINX VIRTUAL HOST
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  vars:
    data: "{{ lookup('file', 'json-files/dns.json') | from_json }}"
  roles:
    - add-nginx-host