- name: add-GENERIC-user
  hosts: "{{ host }}"
  gather_facts: false
  become: true
  vars:
    data: "{{ lookup('file', 'admin-user.json') | from_json }}"
  roles:
    - add-generic-user
    - user-sudo