- name: add-admin-user
  hosts: "{{ host }}"
  gather_facts: false
  become: true
  vars:
    usersdata: "{{ lookup('file', 'json-files/admin-user.json') | from_json }}"
  roles:
    - user-with-ssh
    - user-sudo