- name: DELETE DNS RECORD
  hosts: localhost
  gather_facts: false
  vars:
    dnsrecords: "{{ lookup('file', 'dns.json') | from_json }}"
    apitoken: "ZIcdybXr42m8meUstgFHK-gzhgVa9HVhkvS0A5dT"
  roles:
    - delete-dns-record