- name: odoo-git-clone
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  vars:
    git_repos: "{{ lookup('file', 'git-repo.json') | from_json }}"
    addons_directory: 
                - "/opt/odoo-server/extra_addons/"
                - "/opt/odoo-server/extra-addons/"
  roles:
    - odoo-git-clone
