- name: Update OCA ADDONS from Git
  hosts: "{{ host }}"
  gather_facts: true
  become: true
  vars:
      home_directory: "/opt/odoo-server/extra_addons/oca/"
  roles:
    - odoo-update-oca-addons

   