- name: Update OCA ADDONS from Git
  hosts: "{{ host }}"
  gather_facts: false
  become: true
  vars:
      addons_directory: 
                  - "/opt/odoo-server/extra_addons/oca/"
                  - "/opt/odoo-server/extra-addons/oca/"
                  - "/usr/lib/python3/dist-packages/odoo/extra-addons/oca/"
  roles:
    - odoo-update-oca-addons

   