- name: Prepare NGINX PROXY
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  vars:
    data: "{{ lookup('file', 'json-files/admin-user.json') | from_json }}"
  roles:
    - add-generic-user
    - user-sudo
    - install-nginx-pr